DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_RED)
DEF PLAYERNAME1 EQUS "レッド"
DEF PLAYERNAME2 EQUS "サトシ"
DEF PLAYERNAME3 EQUS "ジャック"

DEF RIVALNAME1 EQUS "グリーン"
DEF RIVALNAME2 EQUS "シゲル"
DEF RIVALNAME3 EQUS "ジョン"
ENDC

IF DEF(_GREEN)
DEF PLAYERNAME1 EQUS "グリーン"
DEF PLAYERNAME2 EQUS "シゲル"
DEF PLAYERNAME3 EQUS "ジョン"

DEF RIVALNAME1 EQUS "レッド"
DEF RIVALNAME2 EQUS "サトシ"
DEF RIVALNAME3 EQUS "ジャック"
ENDC
